<?php

namespace controller;
require_once (__DIR__.'/../../controller/controller.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 14:27:10.
 */
class controllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers controller\controller::insertFormLabel
     * @todo   Implement testInsertFormLabel().
     */
    public function testInsertFormLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controller\controller::getFormfieldData
     * @todo   Implement testGetFormfieldData().
     */
    public function testGetFormfieldData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controller\controller::insertFormSubmit
     * @todo   Implement testInsertFormSubmit().
     */
    public function testInsertFormSubmit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @assert (5, 5) == 25
     * @covers controller\controller::multiplyNumber
     * @todo   Implement testMultiplyNumber().
     */
    public function testMultiplyNumber() {
        $this->assertEquals(25, $this->object->multiplyNumber(5));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
